name: Push and Run

on:
  push:
    branches:
      - main

jobs:
  Build-Laravel-And-Push-Dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .env file for Laravel
        run: |
          cd server/image-editor-server
          cp .env.example .env
          sed -i "s/DB_PASSWORD=\${{ secrets.DB_PASSWORD }}/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/" .env

      - name: Update Node.js database config
        run: |
          cd server/image-editor-chat-server
        
          sed -i 's/password: ""/password: "${{ secrets.DB_PASSWORD }}"/g' server.js

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/editorserver:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/editorserver:latest


      - name: Build Node.js Chat Server Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/chatserver:latest -f Dockerfile.node .


      - name: Push Chat Server Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/chatserver:latest

  Deploy-Laravel-Docker:
    needs: Build-Laravel-And-Push-Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker-compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/editorserver:latest
            docker rmi ${{ secrets.DOCKER_USERNAME }}/chatserver:latest

            docker-compose up -d
            
            # Wait for the database container to be fully ready
            echo "Waiting for database to be ready..."
            sleep 20
            
            # Run migrations inside the laravel container
            docker-compose exec -i ubuntu_server_1 bash php artisan migrate