name: Push and Run

on:
  push:
    branches:
      - main

jobs:
  Build-Laravel-And-Push-Dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - List repository structure
        run: |
          echo "Root directory contents:"
          ls -la
          echo "\nServer directory contents:"
          ls -la server/
          echo "\nRecursive find for dockerfile:"
          find . -name "dockerfile" -o -name "Dockerfile"

      - name: Setup .env file for Laravel
        run: |
          cd server/image-editor-server
          cp .env.example .env
          sed -i "s/DB_PASSWORD=\${{ secrets.DB_PASSWORD }}/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/" .env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build Docker image
        run: |
          # Try to find and use the dockerfile wherever it is
          DOCKERFILE_PATH=$(find . -name "dockerfile" -o -name "Dockerfile" | head -1)
          if [ -z "$DOCKERFILE_PATH" ]; then
            echo "No Dockerfile found in the repository!"
            exit 1
          fi
          
          echo "Found Dockerfile at: $DOCKERFILE_PATH"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/editorserver:latest -f "$DOCKERFILE_PATH" .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/editorserver:latest

  Deploy-Laravel-Docker:
    needs: Build-Laravel-And-Push-Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker-compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/editorserver:latest
            docker-compose up -d
            
            # Wait for the database container to be fully ready
            echo "Waiting for database to be ready..."
            sleep 20
            
            # Run migrations inside the laravel container
            docker-compose exec -T app php artisan migrate --force